'use client';

import {useEffect,useState,type CSSProperties} from 'react';
import './camera-deep.css';
import {CONTEXT,TOY_DEPTHS,softmax,liftedRows,liftGradients,memorySize,reduction,rankOf} from './cameraMechanics';
import {loadSensors,projectPoint,liftPixel,cameraBevCell,type Rig,type Point} from './sensors';

const ROOT='https://github.com/mit-han-lab/bevfusion/blob/main/';
const LABELS=['Lift & memory','Sort & reduce','Gradients & height','Cache & contracts'];
const format=(n:number)=>n.toFixed(3);
function Source({path,children}:{path:string;children:React.ReactNode}){return <a href={ROOT+path} target="_blank" rel="noreferrer">{children} ↗</a>}

export default function CameraBEVLab({point,selected,chapter}:{point:number;selected:string;chapter?:number}) {
  const [localTab,setTab]=useState(0),[logits,setLogits]=useState([Math.log(.1),Math.log(.6),Math.log(.2),Math.log(.1)]);
  const tab=chapter??localTab,embedded=chapter!==undefined;
  const [bin,setBin]=useState(1),[channel,setChannel]=useState(0),[batch,setBatch]=useState(1),[stride,setStride]=useState(8),[bytes,setBytes]=useState(4);
  const [split,setSplit]=useState(false),[sorted,setSorted]=useState(false),[record,setRecord]=useState('B');
  const [gradient,setGradient]=useState(2),[height,setHeight]=useState(1),[slot,setSlot]=useState(0);
  const [changes,setChanges]=useState<string[]>([]),[seg,setSeg]=useState(false);
  const [packet,setPacket]=useState<{rig:Rig;points:Point[]}|null>(null),[error,setError]=useState('');
  useEffect(()=>{let active=true;loadSensors().then(p=>{if(active)setPacket(p)}).catch(e=>{if(active)setError(String(e))});return()=>{active=false}},[]);
  const p=softmax(logits),rows=liftedRows(logits),mem=memorySize(batch,stride,bytes),pool=reduction(split);
  const shown=sorted?pool.sorted:pool.rows,group=pool.groups.find(g=>g.rows.some(r=>r.id===record));
  const traced=pool.rows.find(r=>r.id===record)!;
  const camera=packet?.rig.cameras.find(c=>c.name==='CAM_'+selected.toUpperCase().replaceAll('-','_'));
  const raw=packet?.points[point],projection=camera&&raw?projectPoint(camera,raw):null;
  const xyz=camera&&projection?.visible?liftPixel(camera,projection.u,projection.v,TOY_DEPTHS[bin]):null;
  const cell=xyz?cameraBevCell(xyz):null;
  const upstream=[0,gradient,0,0],grads=liftGradients(logits,upstream);
  const invalid=changes.filter(x=>x!=='RGB content');
  return <section className={`camera-deep${embedded?' embedded-deep':''}`} id="camera-deep">
    {!embedded&&<header className="deep-heading"><div><small>UNDER THE HOOD / CAMERA → BEV</small><h2>Follow the value.<br/><em>Keep its address.</em></h2></div><p>Learning decides what to send. Calibration decides where it goes. Reduction decides what arrives together. Open the machinery behind Lift and Pool.</p></header>}
    {!embedded&&<div className="deep-tabs" role="tablist" aria-label="Camera-to-BEV deep dive" onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();e.stopPropagation();const next=e.key==='Home'?0:e.key==='End'?3:(tab+(e.key==='ArrowRight'?1:3))%4;setTab(next);document.getElementById(`deep-tab-${next}`)?.focus()}}>{LABELS.map((l,i)=><button key={l} id={`deep-tab-${i}`} role="tab" tabIndex={i===tab?0:-1} aria-selected={i===tab} aria-controls="deep-content" onClick={()=>setTab(i)}>{String(i+1).padStart(2,'0')} / {l}</button>)}</div>}
    <div id="deep-content" role={embedded?"region":"tabpanel"} aria-label={embedded?LABELS[tab]:undefined} aria-labelledby={embedded?undefined:`deep-tab-${tab}`} className="deep-content">
    {tab===0&&<>
      <div className="deep-lead"><h3>A pixel does not become one point.</h3><p>Its context vector is copied along depth and scaled by a normalized distribution. Four depth bins and three signed feature channels below isolate the outer product; the real model uses 118 × 80. Channel values are not class probabilities.</p></div>
      <div className="deep-two">
        <div className="deep-controls"><small>EDIT ONE DEPTH LOGIT</small>{TOY_DEPTHS.map((d,i)=><label key={d}>{d} m <output>p = {format(p[i])}</output><input aria-label={`Depth logit at ${d} meters`} type="range" min="-4" max="2" step=".05" value={logits[i]} onChange={e=>setLogits(v=>v.map((x,j)=>j===i?+e.target.value:x))}/></label>)}<p className="deep-equation">Σ p(d) = {format(p.reduce((s,v)=>s+v,0))}</p><button className="deep-reset" onClick={()=>setLogits([Math.log(.1),Math.log(.6),Math.log(.2),Math.log(.1)])}>Restore 0.10 / 0.60 / 0.20 / 0.10</button><p>Changing one logit changes every probability: all four bins share the softmax denominator.</p></div>
        <div className="outer-study"><small>SELECT A WEIGHTED FEATURE / p ⊗ f</small><div className="outer-matrix"><span>depth</span>{CONTEXT.map((f,c)=><strong key={c}>f{c} = {f}</strong>)}{rows.map((r,d)=><div className="outer-row" key={d}><strong>{TOY_DEPTHS[d]} m</strong>{r.map((v,c)=><button key={c} aria-label={`Depth ${TOY_DEPTHS[d]} channel ${c}`} aria-pressed={bin===d&&channel===c} onClick={()=>{setBin(d);setChannel(c)}} style={{'--weight':Math.abs(v)/2,'--tone':v<0?'126,191,211':'236,102,64'} as CSSProperties}>{format(v)}</button>)}</div>)}</div><p className="deep-equation">{format(p[bin])} × {CONTEXT[channel]} = {format(rows[bin][channel])}</p><p>Sum down a channel: {rows.map(r=>format(r[channel])).join(' + ')} = <b>{CONTEXT[channel]}</b>. Probability redistributes the feature; it does not create more of it. Bounds filtering can remove some contributions afterward.</p>
        <div className="address-card"><small>SAME TENSOR INDEX / REAL CALIBRATED RAY</small><p>Return #{point} · {selected} · selected hypothesis {TOY_DEPTHS[bin]} m</p>{error?<p role="alert">{error}</p>:!packet?<p>Loading calibrated sensor packet…</p>:xyz?<><code>feature[n,d,h,w,c] = {format(rows[bin][channel])}</code><code>geometry[n,d,h,w,:] = [{xyz.map(v=>v.toFixed(2)).join(', ')}] m</code><code>raw camera cell = {cell?'['+cell.join(', ')+']':'rejected outside bounds'}</code><p>The feature is illustrative; XYZ comes from the selected return’s real image pixel. Change that return or camera in chapter 01 or 03. Do not mistake these four bins for measured surfaces.</p></>:<p>The shared return is outside this camera. Select a visible return in chapter 01 to inspect its calibrated addresses.</p>}</div></div>
      </div>
      <div className="memory-study"><div><small>THE COST OF MATERIALIZING THE FRUSTUM</small><h3>{mem.mib.toFixed(1)} <em>MiB</em></h3><p>Lifted features alone. Not peak GPU memory or a runtime benchmark.</p></div><div className="memory-controls"><label>Batch <select aria-label="Memory batch" value={batch} onChange={e=>setBatch(+e.target.value)}>{[1,2,4].map(v=><option key={v}>{v}</option>)}</select></label><label>Feature stride <select aria-label="Feature stride" value={stride} onChange={e=>setStride(+e.target.value)}>{[4,8,16].map(v=><option key={v} value={v}>1 / {v}</option>)}</select></label><label>Storage estimate <select aria-label="Storage precision" value={bytes} onChange={e=>setBytes(+e.target.value)}><option value={4}>FP32 · 4 bytes</option><option value={2}>FP16 · 2 bytes</option></select></label><code>[{batch}, 6, 118, {mem.h}, {mem.w}, 80]</code><p>{mem.points.toLocaleString()} spatial hypotheses<br/>{mem.scalars.toLocaleString()} feature scalars</p></div><p>The estimate is B × N × D × H × W × C × bytes / 2²⁰. Halving feature stride multiplies this volume by four. FP16 is a hypothetical storage comparison, not a claim that the reference pooling kernel accepts half precision. Its CUDA path uses float pointers.</p></div>
      <details className="deep-note"><summary>The tensor ledger: reshape changes indexing, not meaning</summary><div className="record-table-wrap"><table className="record-table"><thead><tr><th>Operation</th><th>Shape / selected memory settings</th></tr></thead><tbody>{[
        ['Camera FPN',`[${batch},6,256,${mem.h},${mem.w}]`],
        ['Merge cameras into batch',`[${batch*6},256,${mem.h},${mem.w}]`],
        ['Predict depth + context',`[${batch*6},198,${mem.h},${mem.w}]`],
        ['Broadcast depth × context',`[${batch*6},80,118,${mem.h},${mem.w}]`],
        ['Restore N, permute C to last',`[${batch},6,118,${mem.h},${mem.w},80]`],
        ['Parallel geometric coordinates',`[${batch},6,118,${mem.h},${mem.w},3]`],
        ['Flatten both, same row identity',`[${mem.points.toLocaleString()},80] + [${mem.points.toLocaleString()},3]`],
        ['Append batch, apply shared mask','[M,80] + [M,4]'],
        ['CUDA → channel-first output',`[${batch},1,360,360,80] → [${batch},80,1,360,360]`],
      ].map(([name,shape])=><tr key={name}><td>{name}</td><td>{shape}</td></tr>)}</tbody></table></div><p>M is the number of valid hypotheses, not occupied cells. This ledger keeps the guide’s detection BEV grid fixed while the memory controls vary batch and feature resolution. Changing stride is a scaling experiment, not a different official checkpoint.</p></details>
      <p className="deep-sources"><Source path="mmdet3d/models/vtransforms/lss.py">Outer product</Source> · <Source path="mmdet3d/models/vtransforms/depth_lss.py">Depth-assisted variant</Source></p>
    </>}
    {tab===1&&<>
      <div className="deep-lead"><h3>Sort addresses. Move their values with them.</h3><p>Nine teaching records enter a 3 × 3 × 1 grid. I is outside the bounds. Select an ID, then filter and sort: that same ID, feature and coordinate must travel together. Values include negatives because feature pooling is a sum, not a vote count.</p></div>
      <div className="deep-actions"><button aria-pressed={sorted} onClick={()=>setSorted(!sorted)}>{sorted?'Show incoming records':'Apply mask + shared argsort'}</button><button aria-pressed={split} onClick={()=>setSplit(!split)}>{split?'B is in batch 1':'Move B to a second batch'}</button></div>
      <div className="record-table-wrap"><table className="record-table"><caption>{sorted?'Filtered + sorted':'Incoming order'} · X=3, Y=3, Z=1, B={pool.batches} · channel 0</caption><thead><tr><th>ID</th><th>[x,y,z,b]</th><th>value</th><th>rank</th><th>mask</th></tr></thead><tbody>{shown.map(r=><tr key={r.id} className={record===r.id?'selected':''}><td><button aria-label={`Trace record ${r.id}`} aria-pressed={record===r.id} onClick={()=>setRecord(r.id)}>{r.id}</button></td><td>[{r.x},{r.y},{r.z},{r.b}]</td><td>{r.value}</td><td>{r.x<0?'—':rankOf(r,pool.batches)}</td><td>{r.x<0?'reject':'keep'}</td></tr>)}</tbody></table></div>
      <p className="deep-equation">rank = x(YZB) + y(ZB) + zB + b</p><p>Batch identity is part of the address. Moving B into batch 1 preserves its spatial cell but prevents it from summing with A. Rank is a grouping key, not the CUDA output memory offset.</p>
      <div className="address-card" aria-live="polite"><small>TRACE {record} / ADDRESS ≠ OFFSET</small>{traced.x<0?<p>I is discarded by the shared mask. Its value 99 must contribute to no interval.</p>:<><code>grouping rank = {rankOf(traced,pool.batches)}</code><code>CUDA scalar offset, C=3, channel {channel}:<br/>((((b × Z + z) × X + x) × Y + y) × C + c) = {(traced.b*9+traced.x*3+traced.y)*3+channel}</code><p>Output storage is [B,Z,X,Y,C]. The Python wrapper then permutes to [B,C,Z,X,Y]. The selected channel is carried over from the matrix in chapter 04.</p></>}</div>
      <div className="deep-two"><div className="reduction-study"><h4>Global prefix, then boundary differences</h4><div className="prefix-strip">{pool.sorted.map((r,i)=>{const end=pool.groups.some(g=>g.start+g.rows.length-1===i);return <div key={r.id} className={end?'boundary':''}><small>{r.id}: {r.value}</small><b>{pool.prefix[i]}</b><span>{end?'boundary':'partial'}</span></div>})}</div><p>Only the highlighted prefix values survive. Differences between consecutive surviving values recover each interval sum.</p><code>{pool.groups.map(g=>pool.prefix[g.start+g.rows.length-1]).join(' → ')} → [{pool.groups.map(g=>g.sum).join(', ')}]</code></div><div className="reduction-study"><h4>Independent interval sums</h4>{pool.groups.map(g=><button className="interval-line" key={g.rank} aria-label={`Inspect interval rank ${g.rank}`} aria-pressed={g===group} onClick={()=>setRecord(g.rows[0].id)}><small>rank {g.rank} · start {g.start} · length {g.rows.length}</small><span>{g.rows.map(r=>`${r.id}(${r.value})`).join(' + ')} = <b>{g.sum}</b></span></button>)}<p>One execution lane handles one interval × channel. It reads start + channel, advances by C scalars per source, and writes one final sum. Longer intervals still require more loop iterations; this is not a measured GPU schedule.</p></div></div>
      <details className="deep-note"><summary>Boundary subtlety: floor is not always .long()</summary><p>For valid nonnegative normalized coordinates, truncation and floor agree. The reference casts to integer before testing index bounds, so a normalized coordinate of −0.25 truncates to 0 rather than flooring to −1. This guide uses strict metric bounds for its geometry experiments. Do not copy the cast and assume it rejects every point just below the lower boundary.</p></details>
      <p className="deep-sources"><Source path="mmdet3d/ops/bev_pool/bev_pool.py">Sorting and interval construction</Source> · <Source path="mmdet3d/ops/bev_pool/src/bev_pool_cuda.cu">CUDA forward and backward</Source></p>
    </>}
    {tab===2&&<>
      <div className="deep-lead"><h3>The gradient takes the address book home.</h3><p>Pooling sums values. Its backward pass copies an output gradient to every contributing source—not divided by the number of sources. Geometry and integer ranks receive no gradient through this assignment.</p></div>
      <div className="deep-two"><div className="deep-controls"><label>Upstream gradient at the selected cell <output>{gradient.toFixed(1)}</output><input aria-label="Upstream pooling gradient" type="range" min="-3" max="3" step=".1" value={gradient} onChange={e=>setGradient(+e.target.value)}/></label><p className="deep-equation">y = 7 − 1 − 2 = 4</p><div className="gradient-copies">{['C','D','E'].map(id=><div key={id}><small>∂L / ∂{id}</small><b>{gradient.toFixed(1)}</b></div>)}</div><p>All three sources share the same derivative ∂y/∂x = 1. Negative feature values do not reverse this local derivative.</p></div><div className="reduction-study"><h4>Continue through p(d) × f</h4><p>A separate one-pixel experiment: only the 10 m bin receives this gradient on channel 0 (f₀ = 2). All other incoming gradients are zero. Probabilities carry over from chapter 04.</p><p className="deep-equation">∂L/∂f₀ = Σ p(d)g(d) = {format(grads.feature)}</p><div className="gradient-copies">{grads.logits.map((v,i)=><div key={i}><small>logit / {TOY_DEPTHS[i]} m</small><b>{format(v)}</b></div>)}</div><p>Softmax couples the depth logits: ∂L/∂aₖ = pₖ(f₀gₖ − Σ pⱼf₀gⱼ). Even bins with zero incoming feature gradient can receive logit gradients. Their sum is {format(grads.logits.reduce((s,v)=>s+v,0))}.</p></div></div>
      <div className="layout-study"><div><h4>Flatten height into channels. Do not sum it.</h4><label>Height slices <select aria-label="Height slices" value={height} onChange={e=>{setHeight(+e.target.value);setSlot(0)}}><option value={1}>Z = 1 · configured</option><option value={4}>Z = 4 · teaching comparison</option></select></label><p>At one fixed [b,x,y], select a channel slot. For C=3, concatenating Z slices gives output channel z × 3 + c. Distinct heights stay distinguishable.</p><code>[B,C,Z,X,Y] → [B,C×Z,X,Y]</code></div><div><div className="height-slots">{Array.from({length:height*3},(_,i)=><button key={i} aria-label={`Height output channel ${i}`} aria-pressed={slot===i} onClick={()=>setSlot(i)}><small>z{Math.floor(i/3)} / c{i%3}</small><b>{i}</b></button>)}</div><p className="deep-equation">out[:, {slot}, x, y] = in[:, {slot%3}, {Math.floor(slot/3)}, x, y]</p><p>The real C=80, Z=1 configuration keeps 80 channels. A hypothetical Z=4 would yield 320; downstream layers would need matching channel counts.</p></div></div>
      <p className="deep-sources"><Source path="mmdet3d/ops/bev_pool/src/bev_pool_cuda.cu">Gradient copy kernel</Source> · <Source path="mmdet3d/models/vtransforms/base.py">Z unbind and channel concatenation</Source></p>
    </>}
    {tab===3&&<>
      <div className="deep-lead"><h3>Cache geometry, not assumptions.</h3><p>A precomputed permutation is reusable only for an identical geometric mapping. Changing RGB alone leaves that mapping intact. Changing calibration, preprocessing, discretization or tensor order can make the cached addresses wrong.</p></div>
      <div className="deep-two"><div className="cache-choices"><small>WHAT CHANGED SINCE THE CACHE WAS BUILT?</small>{['RGB content','Camera intrinsics / extrinsics','Resize / crop / image augmentation','Depth bins / BEV grid','BEV augmentation','Camera order / batch layout','Per-frame pose compensation'].map(s=><label key={s}><input type="checkbox" checked={changes.includes(s)} onChange={()=>setChanges(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s])}/>{s}</label>)}</div><div className={`cache-result ${invalid.length?'invalid':''}`} role="status"><small>{invalid.length?'RECOMPUTE BEFORE REUSE':'GEOMETRY CACHE REMAINS VALID'}</small><h3>{invalid.length?'Same camera ≠ same mapping.':'New pixels. Same addresses.'}</h3><p>{invalid.length?invalid.join(' · '):'Reuse valid mask, source permutation and interval starts / lengths. Recompute learned depth, context and weighted feature values for every image.'}</p><code>frustum → metric XYZ → mask → ranks → permutation → intervals</code><p>Contract checker, not a runtime cache benchmark. This real packet uses pose-compensated transforms across sensor timestamps; never assume a single vehicle calibration implies identical per-frame lidar2cam matrices.</p></div></div>
      <div className="config-study"><div className="deep-actions"><button aria-pressed={!seg} onClick={()=>setSeg(false)}>Detection · this guide</button><button aria-pressed={seg} onClick={()=>setSeg(true)}>Segmentation · supplied example</button></div><div className="contract-pairs"><div><small>DEPTH NETWORK</small><b>{seg?'LSSTransform':'DepthLSSTransform'}</b><p>{seg?'Camera features 256 → 198 via 1×1 conv.':'64-channel sparse-depth encoding joins 256 image channels; two 3×3 blocks precede the 198-channel prediction.'}</p></div><div><small>RAW CAMERA GRID</small><b>{seg?'256 × 256 · 0.4 m':'360 × 360 · 0.3 m'}</b><p>{seg?'x,y ∈ [−51.2, 51.2) m':'x,y ∈ [−54, 54) m'} · z ∈ [−10,10), Z=1</p></div><div><small>AFTER STRIDE-2 NETWORK</small><b>{seg?'80 × 128 × 128':'80 × 180 × 180'}</b><p>{seg?'0.8 m per output cell':'0.6 m per output cell'}. Learned spatial downsampling follows pooling.</p></div></div><p>Both examples use 118 bins: 1.0, 1.5, …, 59.5 m; 60 m is excluded. The 198 output channels split into 118 depth logits and 80 context features. This switch compares contracts only; it does not silently change the guide’s detection grid.</p></div>
      <details className="deep-note" open><summary>Paper optimization ≠ every public forward pass</summary><p>The paper describes cached geometry association and interval reduction. The released reference path still constructs geometry and calls argsort in forward; the custom interval kernel is directly visible. Its speedup is a reported result for the paper’s setup, not a browser timing promise. Removing a global prefix scan also does not remove the explicit lifted-feature tensor from this implementation.</p></details>
      <p className="deep-sources"><Source path="configs/nuscenes/seg/fusion-bev256d2-lss.yaml">Segmentation contract</Source> · <Source path="configs/nuscenes/det/transfusion/secfpn/camera+lidar/default.yaml">Detection contract</Source> · <a href="https://arxiv.org/abs/2205.13542" target="_blank" rel="noreferrer">Paper §III-B ↗</a></p>
    </>}
    </div>
  </section>;
}
