'use client';
import {useEffect,useRef,useState} from 'react';
import {HEAD_HEAT,localPeaks,topQueries,decodeBox} from './detection';
import {loadSensors,type Point} from './sensors';
export default function DetectionLab(){
 const [suppress,setSuppress]=useState(true),[selected,setSelected]=useState(23),[dx,setDx]=useState(0),[yaw,setYaw]=useState(90),[logHeight,setLogHeight]=useState(Math.log(3));
 const [points,setPoints]=useState<Point[]>([]),[error,setError]=useState('');const ref=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{let live=true;loadSensors().then(d=>{if(live)setPoints(d.points)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[]);
 const scores=suppress?localPeaks(HEAD_HEAT):HEAD_HEAT,queries=topQueries(scores,2),index=queries.some(q=>q.index===selected)?selected:queries[0].index;
 const qx=80+index%7+.5,qy=110+Math.floor(index/7)+.5;
 const box=decodeBox(qx,qy,dx,0,[Math.log(8),Math.log(2.5),logHeight],-.3,Math.sin(yaw*Math.PI/180),Math.cos(yaw*Math.PI/180));
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;
  const draw=()=>{if(!canvas.isConnected)return;const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=r.width*dpr;canvas.height=r.height*dpr;const c=canvas.getContext('2d')!;c.scale(dpr,dpr);const w=r.width,h=r.height,scale=Math.min(w,h)*.8/20,cx=w/2,cy=h/2;
   const p=(x:number,y:number)=>({x:cx+(x+5)*scale,y:cy-(y-15)*scale});
   c.fillStyle='#f8f6ef';c.fillRect(0,0,w,h);c.strokeStyle='#dedbd1';for(let i=0;i<=20;i+=2){let a=p(-15+i,5),b=p(-15+i,25),d=p(-15,5+i),e=p(5,5+i);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.moveTo(d.x,d.y);c.lineTo(e.x,e.y);c.stroke()}
   c.fillStyle='#20282070';points.forEach(q=>{if(q[0]<-15||q[0]>5||q[1]<5||q[1]>25)return;const s=p(q[0],q[1]);c.fillRect(s.x,s.y,1.2,1.2)});
   const corners=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([a,b])=>{const x=a*box.dims[0]/2,y=b*box.dims[1]/2;return p(box.x+Math.cos(box.yaw)*x-Math.sin(box.yaw)*y,box.y+Math.sin(box.yaw)*x+Math.cos(box.yaw)*y)});
   c.beginPath();corners.forEach((v,i)=>i?c.lineTo(v.x,v.y):c.moveTo(v.x,v.y));c.closePath();c.fillStyle='#d957301a';c.fill();c.strokeStyle='#d95730';c.lineWidth=2;c.stroke();const center=p(box.x,box.y),end=p(box.x+Math.cos(box.yaw)*box.dims[0]/2,box.y+Math.sin(box.yaw)*box.dims[0]/2);c.beginPath();c.moveTo(center.x,center.y);c.lineTo(end.x,end.y);c.stroke();c.fillStyle='#d95730';c.beginPath();c.arc(center.x,center.y,4,0,Math.PI*2);c.fill();
   const seed=p(qx*.6-54,qy*.6-54);c.strokeStyle='#477e9e';c.beginPath();c.arc(seed.x,seed.y,7,0,Math.PI*2);c.stroke();c.font='12px ui-monospace, monospace';c.fillStyle='#424a43';c.fillText('NATIVE LiDAR XY · +Y UP / +X RIGHT',14,22);c.fillText('Real points · orange box is a teaching decode',14,h-16);
  };draw();const ro=new ResizeObserver(draw);ro.observe(canvas);return()=>ro.disconnect();
 },[points,index,dx,yaw,logHeight]);
 return <div className="detection-lab"><div className="query-study"><b>01 / FIND OBJECT QUERIES</b><p>One-class 7 × 7 teaching heatmap. Select one of the two highest-ranked candidates.</p><button className="inverse-toggle" aria-pressed={suppress} onClick={()=>setSuppress(!suppress)}>{suppress?'3 × 3 peak suppression ON':'Peak suppression OFF'}</button><div className="query-heat">{scores.map((v,i)=><button key={i} disabled={!queries.some(q=>q.index===i)} aria-label={`Query cell ${i}, score ${v.toFixed(2)}`} aria-pressed={i===index} onClick={()=>setSelected(i)} className={i===index?'active':''} style={{background:`rgba(105,143,161,${.05+.7*v})`}}>{v.toFixed(2)}</button>)}</div><p className="query-result">Top 2: {queries.map(q=>`#${q.index} (${q.score.toFixed(2)})`).join(' · ')}</p><p>Without peak suppression, nearby cells can spend multiple queries on one peak. The actual configuration selects 200 queries across 10 classes; pedestrian and traffic-cone channels use a special 1 × 1 rule.</p><details><summary>From a peak to a query</summary><p>Gather the BEV feature at the peak and add a class embedding. One 8-head transformer decoder lets queries interact and attend to the full BEV field. Regression predicts center offsets, log dimensions, gravity-center height, sin/cos yaw and velocity. These controls isolate the final decoding arithmetic; they do not simulate learned attention.</p></details></div>
 <div className="box-study"><b>02 / DECODE INTO METERS</b>{error?<p role="alert">{error}</p>:<canvas ref={ref} aria-label="Decoded teaching box over the real LiDAR point cloud"/>}<p>Blue ring: initial query position. Orange: decoded center, footprint and heading. This is not a predicted or annotated box.</p></div>
 <aside className="operator-panel"><b>ONE QUERY / ONE BOX</b><label className="decode-control">Center X offset <strong>{dx.toFixed(1)} cells</strong><input aria-label="Box center X offset" type="range" min="-4" max="4" step=".1" value={dx} onChange={e=>setDx(+e.target.value)}/></label><label className="decode-control">Yaw <strong>{yaw}°</strong><input aria-label="Decoded box yaw" type="range" min="-180" max="180" step="1" value={yaw} onChange={e=>setYaw(+e.target.value)}/></label><label className="decode-control">Log height <strong>{logHeight.toFixed(2)}</strong><input aria-label="Box log height" type="range" min="0" max="1.5" step=".01" value={logHeight} onChange={e=>setLogHeight(+e.target.value)}/></label><dl><div><dt>query (x,y) / cells</dt><dd>{qx}, {qy}</dd></div><div><dt>center X</dt><dd>({qx}+{dx.toFixed(1)})×0.6−54<br/>{box.x.toFixed(2)} m</dd></div><div><dt>center Y</dt><dd>{box.y.toFixed(2)} m</dd></div><div><dt>height = exp(log h)</dt><dd>{box.dims[2].toFixed(2)} m</dd></div><div><dt>gravity-center Z</dt><dd>−0.30 m</dd></div><div><dt>bottom Z = Zg − h/2</dt><dd>{box.zBottom.toFixed(2)} m</dd></div><div><dt>sin yaw / cos yaw</dt><dd>{Math.sin(box.yaw).toFixed(3)} / {Math.cos(box.yaw).toFixed(3)}</dd></div></dl><div className="height-diagram" role="img" aria-label={`Vertical box extent: bottom ${box.zBottom.toFixed(2)} m, gravity center -0.3 m, height ${box.dims[2].toFixed(2)} m`}><span>+3 m</span><div style={{top:`${(3.3-box.dims[2]/2)/8*100}%`,height:`${box.dims[2]/8*100}%`}}/><i style={{top:"41.25%"}}/><small>−5 m</small><b>Zg = −0.30 m</b></div><p>Center units use voxel size 0.075 × output stride 8 = 0.6 m. Dimensions are exponentiated; yaw is atan2(sin, cos). The height correction converts gravity center to bottom center.</p><p className="source-links"><a href="https://github.com/mit-han-lab/bevfusion/blob/main/mmdet3d/core/bbox/coders/transfusion_bbox_coder.py" target="_blank" rel="noreferrer">Official box coder ↗</a></p></aside>
 </div>;
}
