export type Lesson = {id:string;group:string;title:string;question:string;bridge:string;try:string;notice:string;takeaway:string;stage?:number;deep?:number};
export const LESSONS:Lesson[]=[
 {id:'frame',group:'01 / Begin with evidence',title:'One sensor packet',stage:0,question:'What do the sensors actually observe?',bridge:'Start with one real nuScenes frame. Keep the same selected return as we move from camera pixels to a shared ground-plane representation.',try:'Select a point in the cloud, then switch camera views.',notice:'One physical return has one 3D location, but a different image coordinate—or no visibility—in each camera.',takeaway:'The input is not yet a fused representation. It is a set of measurements connected by time and calibration.'},
 {id:'image',group:'02 / Build the camera BEV',title:'Pixels into features',stage:1,question:'What survives the camera encoder?',bridge:'We have located a return in an image. Before any lifting, the image is resized, cropped and encoded; its coordinate system must still match calibration.',try:'Choose a feature location. Toggle “skip inverse crop”.',notice:'The same feature index points to a different physical ray when the crop is not undone.',takeaway:'Features carry visual context. Their image coordinates must be mapped back correctly before metric lifting.'},
 {id:'ray',group:'02 / Build the camera BEV',title:'A pixel becomes a ray',stage:2,question:'A pixel gives direction. What gives depth?',bridge:'Correct image coordinates still do not specify a 3D point. Each depth hypothesis places the same pixel at a different position along its calibrated ray.',try:'Move the depth hypothesis, then select the nearest measured-depth bin.',notice:'The orange hypothesis moves while the measured return stays fixed. A discrete bin may leave a small depth error.',takeaway:'Geometry maps each possible depth to a location. It does not choose which depth the network should believe.'},
 {id:'lift',group:'02 / Build the camera BEV',title:'Distribute the evidence',deep:0,question:'How does uncertainty become a feature cloud?',bridge:'Now give every position on that ray a weight. The depth distribution and the context vector form an outer product: many weighted copies, not a single guessed surface.',try:'Raise one depth logit. Select a signed feature value in the matrix.',notice:'All probabilities rebalance, but summing a feature channel across depth preserves its original value before bounds filtering.',takeaway:'Learned values and geometric addresses form two aligned tensors. The memory cost comes from materializing a feature vector at every hypothesis.'},
 {id:'pool',group:'02 / Build the camera BEV',title:'Many samples, one cell',stage:3,question:'What happens when rays meet?',bridge:'The lifted feature cloud is too large to fuse directly with LiDAR. Samples landing in the same BEV cell must be collected into one feature vector.',try:'Select an occupied cell, then inspect its contributing values.',notice:'The destination contains their sum—not their mean, maximum or count.',takeaway:'Pooling changes the representation from samples along rays to features at metric grid addresses.'},
 {id:'reduce',group:'02 / Build the camera BEV',title:'Make pooling efficient',deep:1,question:'How can the GPU sum those cells efficiently?',bridge:'The arithmetic is simple; arranging the data is the engineering problem. Put equal addresses next to each other, keeping every value attached to its source record.',try:'Trace record B through mask + sort, then move it into a second batch.',notice:'The record keeps its value. Changing batch identity changes its group, even at the same spatial cell.',takeaway:'A shared permutation produces contiguous intervals. Each cell-channel interval can be reduced independently, without a global prefix scan.'},
 {id:'gradients',group:'02 / Build the camera BEV',title:'Learn through the sum',deep:2,question:'Can the camera branch learn through pooling?',bridge:'We know where features arrive and how they are summed. Training sends gradients back through the same address book to the depth and context predictors.',try:'Change the upstream gradient. Compare Z=1 with Z=4 and select a height-channel slot.',notice:'Contributors receive the same local pooling gradient. Height concatenation preserves slices in separate channels rather than adding them.',takeaway:'Values remain differentiable through multiplication and summation. Integer cell assignment is fixed geometry, not a learned routing decision.'},
 {id:'lidar',group:'03 / Bring the branches together',title:'Encode measured geometry',stage:4,question:'What does LiDAR contribute differently?',bridge:'The camera branch has reached BEV. LiDAR starts from measured 3D positions, so it can preserve geometric structure through sparse voxel encoding before reaching that same interface.',try:'Increase the XY voxel size and inspect the selected return’s neighbors.',notice:'Voxel membership changes with physical cell size. The fine model grid retains more spatial detail than a coarse teaching grid.',takeaway:'The two branches reach BEV by different routes: uncertain camera lifting versus measured sparse 3D geometry.'},
 {id:'align',group:'03 / Bring the branches together',title:'Agree on one address',stage:5,question:'Do matching shapes mean matching places?',bridge:'Both branches now have BEV tensors. Equal dimensions are not enough: corresponding cells must describe the same patch of the world.',try:'Inject camera yaw error, then restore calibration.',notice:'Camera evidence moves even though the LiDAR measurement does not. Restoring the transform recovers the original location.',takeaway:'Fusion requires a shared coordinate convention, origin, resolution and timing—not merely compatible tensor shapes.'},
 {id:'cache',group:'03 / Bring the branches together',title:'Know what can be cached',deep:3,question:'When is the address book reusable?',bridge:'Alignment depends on geometry. A cached mapping is useful only while those geometric assumptions stay valid; a different model configuration may require a different grid entirely.',try:'Change RGB only, then change crop or calibration. Compare the two configuration contracts.',notice:'Appearance alone preserves addresses. Geometric changes invalidate the cache. Detection and segmentation examples must not be mixed.',takeaway:'Cache the deterministic mapping under an explicit contract. Recompute learned features for each image, and rebuild addresses when the contract changes.'},
 {id:'fuse',group:'03 / Bring the branches together',title:'Mix aligned features',stage:6,question:'What does fusion actually compute?',bridge:'Now the two branches address the same ground cells. Concatenate their channels, then use a learned local convolution to mix visual context and geometry.',try:'Select an output cell. Zero the camera or LiDAR input while keeping weights fixed.',notice:'Its 3 × 3 neighborhood and channel contributions explain the new output. This is not a blend of confidence maps.',takeaway:'BEVFusion separates alignment from learned feature mixing. A fuser can combine evidence; it cannot make an incorrect coordinate system correct.'},
 {id:'head',group:'04 / Read the result',title:'Features into predictions',stage:7,question:'How does the shared field become an answer?',bridge:'A fused feature field is still not a set of objects. A task head selects queries, reasons over BEV and decodes outputs in physical units.',try:'Toggle peak suppression, select a query, and adjust the decoded box.',notice:'Query selection and decoding are distinct steps. Offsets, log dimensions and yaw representations must be converted correctly.',takeaway:'The head turns a shared BEV representation into task-specific outputs. The official reel shows real model results, separate from the teaching box.'},
 {id:'review',group:'04 / Read the result',title:'Put the argument together',question:'Why is this representation useful?',bridge:'You have followed measurements into features, lifted and reduced them into BEV, aligned both branches, and decoded an answer. Now connect the mechanisms to the paper’s claims and limits.',try:'Use the theory notes to revisit supervision, the map head and failure cases.',notice:'The contribution is the combination of dense camera semantics, efficient transformation and a shared metric interface—not a mysterious fusion formula.',takeaway:'BEVFusion is a practical architecture because it gives different encoders a common spatial contract. Its reliability still depends on data, calibration, training and deployment conditions.'},
];
export function lessonFromHash(hash:string){
 const id=hash.replace(/^#/,'');
 if(id==='camera-deep')return 3;
 const index=LESSONS.findIndex(l=>l.id===id);
 return index<0?0:index;
}
